spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate  #启动的时候做格式验证
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: redis  #session会话存储类型
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        min-idle: 1
    timeout: 3000s
    database: 1

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    enable-spring-el-compiler: true

  profiles:
    active: dev
  devtools:
    restart:
      exclude: templates/**,static/**,webjars/** #排除在devtools热部署重启时不需要加载

  servlet:
    multipart:
      enabled: true
      location: /home/caychen/images/  #本地路径
      file-size-threshold: 5MB
      max-request-size: 20MB

logging:
  level:
    org.hibernate.SQL: debug

server:
  error:
    whitelabel:
      enabled: false #禁止将whitelabel直接显示在浏览器上

cdn:
  prefix: http://pxjlwhmqx.bkt.clouddn.com/

qiniu:
  access-key: nLJK0EFllX_FNVbRiDvwmxVyd76PGKyQ3GScEgWx
  secret-key: ZxC2tgtvn2h89YSFhIQdtvvXEvUbSIHVXtibu0x9
  bucket: caychen-file
  cdn-prefix: http://pxjlwhmqx.bkt.clouddn.com
